### ISSUE TITLE
Cannot build for darwin/arm64

### ISSUE THREAD

**Issue by hazcod** [ory/xgoreleaser#2]
Hi! Trying to use this image returns:
```
   ⨯ build failed after 109.27s error=failed to build for darwin_arm64: # runtime/cgo
148
gcc: error: arm64: No such file or directory
149
gcc: error: unrecognized command line option '-arch'; did you mean '-march='?
```

https://github.com/hazcod/github-duo-ssh-ca/pull/7/checks?check_run_id=3300953793

**Comment by aeneasr** [comment]
The image does not support darwin arm64 yet, you would need to add that first!

**Comment by hazcod** [comment]
Hmm, how would it support it if I may ask?
osxcross mentions `arm64 requires macOS 11.0 SDK (or later).` and here we use 10.15
I've opened up https://github.com/ory/xgoreleaser/pull/3 to fix.
